name       : python-pluginbase
version    : 1.0.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/3d/3c/fe974b4f835f83cc46966e04051f8708b7535bac28fbc0dcca1ee0c237b8/pluginbase-1.0.0.tar.gz : 497894df38d0db71e1a4fbbfaceb10c3ef49a3f95a0582e11b75f8adaa030005
license    : BSD-3-Clause
component  : programming.python
summary    : PluginBase is a module for Python that enables the development of flexible plugin systems in Python.
description: |
    PluginBase is a module for Python that enables the development of flexible plugin systems in Python.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
